[package]
name = "rusty-spring"
version = "0.1.0"
authors = ["-- <samuel.young.103@gmail.com>"]

[dependencies]
gl = "0.6"
libc = "0.2"
os_type ="2.2"
rlibc = "1.0.0"
vulkano = "0.11"
winit = "0.18"
vulkano-win= "0.11"
