[package]
name = "rusty-spring "
version = "0.0.1"
authors = ["moonLightFires"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
[dependencies.amethyst]
version = "0.15"
default-features = true
features= ["vulkan"]
